"""empty message

Revision ID: f0b48036a18e
Revises: 5825e25f1b3a
Create Date: 2024-03-15 16:47:00.600509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b48036a18e'
down_revision = '5825e25f1b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=128), nullable=True))
        batch_op.drop_column('_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_title', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
